clear all
load('Crani.mat');

FA = eye(4);

min = max(fv.vertices(3,:));

fv.vertices(:,4) = ones(size(fv.vertices,1),1); % Añadir fila de 1 para poder trasladar
fv.vertices = fv.vertices'; % Transponer para hacer la multiplicacion

%fv.vertices = transl(0,0,-min)*fv.vertices; %rotamos y centramos a la mesa
FA = transl(0,0,min)*FA; 

fv.vertices = fv.vertices(1:3,:);
fv.vertices = fv.vertices';

trplot(FA, ... 
    'frame', 'A', ...
    'color', 'r',...
    'text_opts', {'FontSize', 10, 'FontWeight', 'bold'},...
     'length',100,...
    'arrow',...
    'axis',[-1 1 -1 1 -1 1],...
    'view',[150,30],...
    'width', 1.2);

hold on

x = 0;
y = 0;
z = min;
scatter3(x,y,z,'filled');

trplot(eye(4), ... 
    'frame', 'origen', ...
    'color', 'b',...
    'text_opts', {'FontSize', 10, 'FontWeight', 'bold'},...
     'length',100,...
    'arrow',...
    'axis',[-1 1 -1 1 -1 1],...
    'view',[150,30],...
    'width', 1.2);

% patch(fv,'FaceColor',       [0.7 0.5 0.9], ...
%          'EdgeColor',       'none',        ...
%          'FaceLighting',    'gouraud',     ...
%          'AmbientStrength', 0.15);
     
camlight('headlight');
material('shiny');

axis([-150 200 -150 200 -150 200]);
