language: java
os: osx
osx_image: xcode9.3
before_install:
 - mkdir lib
 - git clone --depth 50 https://github.com/petercorke/toolbox-common-matlab lib/toolbox-common-matlab
 - git clone --depth 50 https://github.com/petercorke/spatial-math lib/spatial-math
install: source /dev/stdin <<< "$(curl -sL https://ssd.mathworks.com/supportfiles/matlab-runner/install)"
script:
 - matlab-runner -xi .git -xi doc -xi lib/spatial-math/.git -xi lib/spatial-math/doc -xi lib/toolbox-common-matlab/.git -sd unit_test "RunAllTests"
after_success:
 - bash <(curl -s https://codecov.io/bash)
